version: '3.9'

services:
  api:
    container_name: calendario-easy-api
    build: ./
    restart: always
    ports:
      - "3000:3000"
    depends_on:
      - postgres
    environment:
      DATABASE_URL: postgres://postgres:postgres@postgres:5432/calendarioeasy
    volumes:
      - ./:/app

  postgres:
    image: postgres:15
    container_name: calendario-easy-db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: calendarioeasy
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
