version: '3.8'

services:
  api:
    build: .
    container_name: calendario-easy-api
    depends_on:
      - db
    ports:
      - '3000:3000'
    environment:
      DATABASE_URL: postgres://postgres:postgres@db:5432/calendar_easy
    volumes:
      - .:/app
    command: sh -c "npx prisma migrate deploy && npm run start:prod"

  db:
    image: postgres:15
    container_name: calendario-easy-db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: calendar_easy
    ports:
      - '5432:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    container_name: calendario-easy-pgadmin
    restart: always
    ports:
      - '5050:80'
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    depends_on:
      - db

volumes:
  pgdata:
